name: Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Use NodeJS 16"
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: "Setup npm"
        run: |
          npm set @xcanchal:registry=https://npm.pkg.github.com/xcanchal
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"
      - name: Install dependencies
        run: |
          yarn install --immutable --immutable-cache --check-cache
          npx lerna bootstrap
      - name: Run tests
        run: npx lerna exec npm run test
