name: Publish to npmJS
on: push

# on:
#   # When Release Pull Request is merged
#   pull_request:
#     branches:
#       - main
#     types: [closed]

permissions:
  contents: write # for checkout and tag
  pull-requests: write # for comments
  packages: write # for publish

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  publish-npm:
    needs: [tests]
    permissions:
      contents: write
    if: |
      startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.npm_token }} # set this token manually
    steps:
      - name: "Checkout" # Download code from the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Checkout all branches and tags
          ref: "${{ github.event.pull_request.base.ref }}"
          token: ${{ secrets.GITHUB_TOKEN }} # this token is available by default

      # setup .npmrc using NODE_AUTH_TOKEN
      - name: Setup .npmrc file for publish
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Configure Git User
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Check if able to publish changes
        run: npm whoami # will throw and exit if npm is not ready to publish

      - name: "Install dependencies"
        run: yarn install --immutable --immutable-cache --check-cache

      - name: "Publish to npmJS"
        run: yarn run publish --yes
        env:
          NODE_AUTH_TOKEN: "${{secrets.npm_token}}"
