name: Publish to npmJS
on:
  workflow_run:
    workflows: ["Tests"]
    branches: [main]
    types:
      - completed
  # When Release Pull Request is merged
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: write # for checkout and tag
  pull-requests: write # for comments
  packages: write # for publish

jobs:
  publish-npm:
    needs: test
    permissions:
      contents: write
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout" # Download code from the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Checkout all branches and tags
          ref: "${{ github.event.pull_request.base.ref }}"

      - name: Get Node.js version
        id: nvm
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org/"
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn run publish --yes
        env:
          NODE_AUTH_TOKEN: "${{secrets.npm_token}}"
